export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_REFERRER = 'SET_REFERRER';
export const CATEGORY_GO_DOWN = 'CATEGORY_GO_DOWN';
export const CATEGORY_GO_UP = 'CATEGORY_GO_UP';
